### ISSUE TITLE
Session establishment failed - No PFCP association

### ISSUE THREAD

**Issue by orion-belt** [travelping/upg-vpp#93] opened 2021-03-02 14:30 UTC
I am getting this issue of session establishment with cause "no established pfcp association".
In pcap it can be seein that pfcp node has associated with upg.

[session_fail.zip](https://github.com/travelping/upg-vpp/files/6069323/session_fail.zip)

```
$ docker exec -it vpp-upf vppctl show upf association
Node: 192.168.61.196
  Recovery Time Stamp: 2021/03/02 14:19:02:000
  Sessions: 0
```

**Comment by RoadRunnr** [comment] 2021-03-07 20:06
can you provide an pcap of the PFCP exchange, starting with the the Association Request, please?

**Comment by orion-belt** [comment] 2021-03-08 08:49
Hi @RoadRunnr,
It is already there in above message.
(I am using image-debug of upg-vpp)

> In pcap it can be seen that pfcp node has associated with upg.
> 
> [session_fail.zip](https://github.com/travelping/upg-vpp/files/6069323/session_fail.zip)

**Comment by RoadRunnr** [comment] 2021-03-08 10:47
Sorry for missing the file.

@ivan4th needs to take a look at that. My first suspicion would be a problem with the Node Id AVP, but it could be something else.

**Comment by ivan4th** [comment] 2021-03-09 14:20
Yes, I will take a look at that, looks like IPv4 Node ID lookup is not done correctly due to `ip46_address_t` with uninitialized bytes being used as a hash key. Thanks for the report

**Comment by RoadRunnr** [comment] 2021-03-22 07:49
@ivan4th has this been fixed in the meantime?

**Comment by ivan4th** [comment] 2021-03-22 11:59
@orion-belt sorry, it was a bit of red herring. After trying to reproduce the problem I understood there's really no bug in the Node ID handling code and IP-based Node IDs are handled just fine. The actual problem here is clock skew. Please note that at 14:19:02 your control plane sends PFCP Association Setup Request with Recovery Timestamp at 14:11:17 UTC, so basically the association is already expired even before it's started; that's also why there are no PFCP Heartbeat Requests _from the UPG side_ in the next 50s before a Heartbeat Request from the control plane. So, please adjust the clock and try again :)

<img width="1410" alt="Screenshot 2021-03-22 at 14 55 37" src="https://user-images.githubusercontent.com/190448/111986272-c8424c80-8b1e-11eb-9d0a-3fb02c09fbd3.png">

**Comment by RoadRunnr** [comment] 2021-03-22 12:54
@ivan4th your explanation make no sense to me. Having a Recovery Timestamps in the past is perfectly ok. There would only be a problem when it is in the future.

**Comment by ivan4th** [comment] 2021-03-22 13:23
@RoadRunnr yes, you're correct. Trying to understand why no heartbeat requests are sent from the UPG though...

**Comment by orion-belt** [comment] 2021-04-02 08:41
@ivan4th @RoadRunnr 
One different thing I noticed here here is IE Enterprise specific type is different in association response and session establishment response.

Is could be the reason for session failure ?

**Closed** 2021-04-07 16:07 UTC
